# Generated by Django 5.1.6 on 2025-02-26 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="제목")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="이름")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
            ],
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tabom.article")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tabom.user")),
            ],
        ),
    ]
